// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msvrravaizusgizlukbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdnJyYXZhaXp1c2dpemx1a2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NzQzMTEsImV4cCI6MjA1NzQ1MDMxMX0.tPElGDo8Ug4F0VeaQ1irZ7tmfN3ZOjpsmmHMGv6ZNLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);